V11.0.7 beta
DephyInc/Actuator-Package pull request #114
Opened 2023-07-18 22:11 UTC by jcoughlin11

# Description
Adds training methods and streamlines firmware version validation.

# Requirements
- [ ] Tested on Windows.
- [ ] Tested on Linux.
- [ ] Tested on RPi.
- [ ] Connected ActPack and runs scripts.

2023-08-03 13:53 UTC, jcoughlin11 commented
#115 addressed in 4231c05

2023-08-03 13:58 UTC, Sotilrac commented
@jcoughlin11 any specific tests we should be running, and what should we expect the result to be?

2023-08-04 18:49 UTC, jcoughlin11 commented
@Sotilrac I've run the demos on linux, but I still need to run them on Windows and the Pi. I also would like to test the bootloader with it.

2023-08-07 21:54 UTC, jcoughlin11 commented
@Sotilrac @randop81 This has been tested and should be good to go. If you wouldn't mind reviewing it when you get a chance, I'd appreciate it. Thanks!

2023-08-08 15:59 UTC, Sotilrac requested changes
I loe the new docs. Great initiative!

2023-08-08 15:59 UTC, Sotilrac commented on docs/source/_static/logo-d.svg
Could we use this logo instead:
https://dephy.com/images/logo-dephy.png

Luke has been trying to phase out this "D" logo. But if the logo needs to be tiny, the one linked might not work

2023-08-08 18:18 UTC, jcoughlin11 commented on docs/source/_static/logo-d.svg
I tried, but it doesn't appear to have worked: https://flexsea.readthedocs.io/en/latest/#

Would it be possible to get an svg version of that image?

2023-08-08 18:44 UTC, jcoughlin11 commented on docs/source/_static/logo-d.svg
@Sotilrac  Nvm. I changed the logo. Let me know what you think: https://flexsea.readthedocs.io/en/latest/

2023-08-08 18:44 UTC, jcoughlin11 commented on docs/source/_static/logo-d.svg
The only other thing is that the D logo is being used as the favicon for the docs. Should that be changed, kept, or do we want to just not have a favicon?

2023-08-08 20:07 UTC, Sotilrac approved these changes

2023-08-08 20:07 UTC, merged