EMBD-632 Unify Bootloader Scripts
DephyInc/Actuator-Package pull request #61
Opened 2021-02-19 21:32 UTC by teginyucelmayadagli

# Description
Bootloader python script returns error if any

# Changes
- Added return status for called functions

# Test Plan
Can be tested on any ActPack or Exo with bootloader. 
https://dephy.com/wiki/flexsea/doku.php?id=actpackfieldupdate

# Expected Results
Shall return bootloader status 

# Requirements
- Flexsea-build (Same branch name EMBD-632)

2021-03-06 01:15 UTC, AliaLayne approved these changes
I don't know if this was done already! But here's my 2 cents.  In addition to my single comment.  I would consider adding some more comments throughout the code.  It doesn't need many.  The variable names are fully written out, which makes it very understandable without them.  But I do think a few would be helpful.

2021-03-06 01:15 UTC, AliaLayne commented on Python/flexsea_demo/bootloader.py
> +	result = False
If the line:

result = bootloader(flex.FlexSEA(), args.port[0], args.baud_rate, args.target)

is sending back a value.  Won't the value in the line above be overwritten?  If so, do you need it?  If you do need it, maybe there is something wrong with the bootloader function?

Just an observation.

2021-03-16 18:00 UTC, JFDuval commented on Python/flexsea_demo/bootloader.py
> +	result = False
@teginyucelmayadagli can you take a look at this? Fix or resolve

2021-03-16 18:01 UTC, JFDuval approved these changes
Looks good to me, and works. Please address Alia's comment before merging.

2021-03-16 18:02 UTC, Sotilrac requested changes

2021-03-16 18:02 UTC, Sotilrac commented on Python/flexsea_demo/bootloader.py
> +	result = False
You can loose the result variable altogether, just `return bootloader(flex.FlexSEA(), args.port[0], args.baud_rate, args.target)` at the end

2021-03-16 18:14 UTC, teginyucelmayadagli commented on Python/flexsea_demo/bootloader.py
> +	result = False
Addressed the issue

2021-03-16 21:01 UTC, Sotilrac approved these changes

2021-03-16 22:11 UTC, merged