CON-147 Convert Exo to EB5x
DephyInc/Actuator-Package pull request #74
Opened 2021-07-12 19:20 UTC by AliaLayne

2021-07-13 17:56 UTC, Sotilrac requested changes
Looks good.

2021-07-13 17:56 UTC, Sotilrac commented on .pre-commit-config.yaml
> --   repo: https://github.com/jumanjihouse/pre-commit-hooks
[REQUIRED] please remove this change. You can disable it locally if you need to like this
```bash
SKIP=forbid-space-in-indent  pre-commit run --all-files
```

2021-07-13 18:36 UTC, AliaLayne commented on .pre-commit-config.yaml
> --   repo: https://github.com/jumanjihouse/pre-commit-hooks
It's done.  But, to be clear.  I don't have time to do this PR right now.  It's incomplete.  Nothing has been tested.  The python had not been updated.  The c-code has not been updated.  This only updates the structs and python definitions.  It should not be merged with develop until the minimum requirements listed have been completed.

2021-07-14 19:26 UTC, Sotilrac approved these changes

2021-07-19 19:55 UTC, Sotilrac approved these changes

2021-07-19 19:56 UTC, merged