[DSEP-191] Recompiles libraries for Ubuntu 20.04
DephyInc/Actuator-Package pull request #87
Opened 2022-01-27 15:06 UTC by jcoughlin11

# Description

When fx_plan_stack/stack_builder.sh is run on Ubuntu 21.10, the resulting compiled libraries are incompatible with older versions owing to the newest version of clib6 being unavailable. This PR simply recompiles the libraries necessary for flexsea to work on Ubuntu 20.04.

# Changes

* [DSEP-191]

# Test Plan

1. Run the demo scripts on Windows, linux, and raspbian.

# Expected Results

* All demos run as expected.

# Requirements
Edit the list accordingly.
- [ ] Tested on Windows.
- [ ] Tested on Linux.
- [ ] Tested on RPi.
- [ ] Connected ActPack and runs scripts.

2022-01-27 19:45 UTC, Sotilrac requested changes
I get this error:

```bash
FlexSEA libraries loaded
Traceback (most recent call last):
  File "./version.py", line 79, in <module>
    sys.exit(main())
  File "./version.py", line 62, in main
    fw_array = get_version(flex.FlexSEA(), args.port[0], args.baud_rate)
  File "/home/carlos/venv/actpack/lib/python3.8/site-packages/flexsea/flexsea.py", line 24, in __init__
    self.__load_c_libs()
  File "/home/carlos/venv/actpack/lib/python3.8/site-packages/flexsea/flexsea.py", line 96, in __load_c_libs
    self.__define_c_args()
  File "/home/carlos/venv/actpack/lib/python3.8/site-packages/flexsea/flexsea.py", line 133, in __define_c_args
    self.c_lib.fxReadMdDeviceAll.argtypes = [
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/carlos/venv/actpack/lib/python3.8/site-packages/flexsea/libs/linux/libfx_plan_stack.so: undefined symbol: fxReadMdDeviceAll

```

it seems we need to build using the MD devices

2022-01-27 20:07 UTC, Sotilrac commented
@jcoughlin11  I pushed some updates and fixed the issue with ubuntu. Please test on your end
I also, fixed a security issue with pillow 8 and pushed to pypi

2022-01-27 20:08 UTC, Sotilrac approved these changes

2022-01-28 15:36 UTC, jcoughlin11 commented
@Sotilrac Looks good! The demos run for me, so I think this can be merged

2022-02-02 05:05 UTC, merged